<template>
    <main>
        <aside>
            <ul>
                <li>Dasboard</li>
                <li>Settings</li>
                <li>Notifications</li>
                <li>Logout</li>
            </ul>
        </aside>
        <slot></slot>
    </main>
</template>